let questions = [
    {
      question: "Wer hat HTML erfunden?",
      answer_1: "Robbie Williams",
      answer_2: "Lady Gaga",
      answer_3: "Tim Berners-Lee",
      answer_4: "Justin Bieber",
      right_answer: 3,
    },
    {
      question: "Was bedeutet die Abkürzung CSS?",
      answer_1: "Cascading Style Sheets",
      answer_2: "Creative Software Solutions",
      answer_3: "Computer System Security",
      answer_4: "Centralized System Structure",
      right_answer: 1,
    },
    {
      question:
        "Welche Programmiersprache wird häufig für die Interaktivität auf Webseiten verwendet?",
      answer_1: "JavaScript",
      answer_2: "Python",
      answer_3: "Ruby",
      answer_4: "C++",
      right_answer: 1,
    },
    {
      question: "Welcher HTML-Tag wird verwendet, um eine Tabelle zu erstellen?",
      answer_1: "<table>",
      answer_2: "<form>",
      answer_3: "<div>",
      answer_4: "<header>",
      right_answer: 1,
    },
    {
      question: "Was ist der Zweck von Bootstrap?",
      answer_1: "Ein Framework für Webdesign und responsive Layouts",
      answer_2: "Ein CMS für die Webentwicklung",
      answer_3: "Ein JavaScript-Plugin zur Bildbearbeitung",
      answer_4: "Ein Tool zur Serveradministration",
      right_answer: 1,
    },
    {
      question: "Was ist ein DOM in Bezug auf Webentwicklung?",
      answer_1: "Document Object Model",
      answer_2: "Design Optimization Method",
      answer_3: "Data Output Manager",
      answer_4: "Direct Online Management",
      right_answer: 1,
    },
    {
      question: "Welche der folgenden Eigenschaften gehört zu CSS?",
      answer_1: "font-size",
      answer_2: "getElementById",
      answer_3: "console.log",
      answer_4: "SELECT",
      right_answer: 1,
    },
    {
      question: "Was bedeutet 'responsive Webdesign'?",
      answer_1: "Webseiten passen sich an verschiedene Bildschirmgrößen an",
      answer_2: "Webseiten haben eine schnelle Ladezeit",
      answer_3: "Webseiten sind sicher vor Angriffen",
      answer_4: "Webseiten enthalten interaktive Elemente",
      right_answer: 1,
    },
    {
      question: "Was ist der Unterschied zwischen GET und POST in HTTP-Anfragen?",
      answer_1:
        "GET überträgt Daten in der URL, POST überträgt sie im Body der Anfrage",
      answer_2: "GET ist schneller als POST",
      answer_3: "GET wird nur für Formulare verwendet, POST für API-Aufrufe",
      answer_4: "POST ist sicherer als GET",
      right_answer: 1,
    },
    {
      question: "Welche der folgenden ist ein bekanntes JavaScript-Framework?",
      answer_1: "React",
      answer_2: "Angular",
      answer_3: "Vue",
      answer_4: "Alle der oben genannten",
      right_answer: 4,
    },
  ];